# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4274169324fae84d038883e125008cd31535beae19bebb0eb1d5904a509848563783508b0c2b6aad7907568c81b4f5148e7c62180c64cac6e6ca77c49d181721

test:
  secret_key_base: 2f300be5c6d3ccb493990044bf905e391241a6bb4848873b857962a5c5031a3ef6d4db97a05c668e871bddb063c5fb91fac17e0593ac8b4818c9b57e827d0095

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
